const actionTypes = {
    FETCH_CASE_SUCCESS: 'FETCH_CASE_SUCCESS',
    FETCH_CASE_REQUESTED: 'FETCH_CASE_REQUESTED',
    FETCH_CASE_ERROR: 'FETCH_CASE_ERROR',
    FETCH_COMPARED_CASE_SUCCESS: 'FETCH_COMPARED_CASE_SUCCESS',
    FETCH_COMPARED_CASE_ERROR: 'FETCH_COMPARED_CASE_ERROR',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_REQUESTED: 'FETCH_DATA_REQUESTED',
    FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
    CASE_PARAM_SETTED: 'CASE_PARAM_SETTED',
    CASE_PARAM_REMOVED: 'CASE_PARAM_REMOVED',
    FETCH_PEGASET_REQUESTED: 'FETCH_PEGASET_REQUESTED',
    FETCH_PEGASET_SUCCESS: 'FETCH_PEGASET_SUCCESS',
    FETCH_PEGASET_ERROR: 'FETCH_PEGASET_ERROR',
    SET_PEGASET_REMOVE: 'SET_PEGASET_REMOVE',
    FETCH_SCHEMA_SUCCESS: 'FETCH_SCHEMA_SUCCESS',
    FETCH_SCHEMA_REQUESTED: 'FETCH_SCHEMA_REQUESTED',
    FETCH_SCHEMA_ERROR: 'FETCH_SCHEMA_ERROR',
    SCHEMA_DATA_SETTED: 'SCHEMA_DATA_SETTED',
    FETCH_SCHEMA_LIST_SUCCESS: 'FETCH_SCHEMA_LIST_SUCCESS',
    FETCH_SCHEMA_LIST_REQUESTED: 'FETCH_SCHEMA_LIST_REQUESTED',
    FETCH_SCHEMA_LIST_ERROR: 'FETCH_SCHEMA_LIST_ERROR',
    DELETE_SCHEMA_SUCCESS: 'DELETE_SCHEMA_SUCCESS'
  };
  
  export default actionTypes;
  