const actionTypes = {
    FETCH_CASE_SUCCESS: 'FETCH_CASE_SUCCESS',
    FETCH_CASE_REQUESTED: 'FETCH_CASE_REQUESTED',
    FETCH_CASE_ERROR: 'FETCH_CASE_ERROR',
    FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
    FETCH_DATA_REQUESTED: 'FETCH_DATA_REQUESTED',
    FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
    CASE_PARAM_SETTED: 'CASE_PARAM_SETTED',
    CASE_PARAM_REMOVED: 'CASE_PARAM_REMOVED',
    FETCH_PEGASET_REQUESTED: 'FETCH_PEGASET_REQUESTED',
    FETCH_PEGASET_SUCCESS: 'FETCH_PEGASET_SUCCESS',
    FETCH_PEGASET_ERROR: 'FETCH_PEGASET_ERROR',
    SET_PEGASET_REMOVE: 'SET_PEGASET_REMOVE'
  };
  
  export default actionTypes;
  